### ISSUE TITLE
Missing checks.inc.php

### ISSUE THREAD

**Issue by alesc** [diegargon/trackerm#1]
Hola !

your project seems interesting but when I try it I have this beautiful error message : 

```
Warning: require(include/checks.inc.php): failed to open stream: No such file or directory in ./include/common.inc.php on line 25

Fatal error: require(): Failed opening required 'include/checks.inc.php' (include_path='.:/usr/share/php') in ./include/common.inc.php on line 25
```

did you forget to commit some files ? 
Regards,
Alesck

**Comment by diegargon** [comment]
hello. 
Beware, this project it's in very very early stages, ATM it's only ONE week old of "fast coding", that mean  bugs, security problems, (really  no security checks) and missing lots of features , like tracking shows for download, automatic move downloaded torrents and many others.

Language support es-ES and en-EN but primary is es-ES probably some keywords will be missing in en-En in next updates and give it a warning  (anyway its easy editing "lang.inc.php")

probably there will be changes between versions (commits) that forces to delete the databases (under / cache) and start over.
There is nothing fixed at the moment in this code and it will surely take a while to make things consistent between commit. 

Expect you need to reconfigure / recreate the library database (deleting old) anytime,  as long as there is no a release version.

Expect bad english too :)

 check.inc.php problem its fixed.

**Comment by alesc** [comment]
This is promising,I will let you work on your project and I will test it in some time. 
When time will come I will maybe contribute (ex: translations in EN/FR and some bugfixes or functionality ideas)

¡ hasta luego !
